{
	"Animated": true,
	"Duration": 2,
	"IsIconHidden": true,
	"Message": "Sync Started",
	"OnFailure": "/DemoApp/Actions/Service/SyncFailureMessage.action",
	"OnSuccess": "/DemoApp/Actions/Service/UploadOffline.action",
	"_Type": "Action.Type.ToastMessage"
}