{
	"OnFailure": "/SAPAssetManager/Actions/ZSyncFail.action",
	"OnSuccess": "/SAPAssetManager/Actions/ZDowmload.action",
	"Service": "/SAPAssetManager/Services/AssetManager.service",
	"_Type": "Action.Type.OfflineOData.Upload"
}